
export const WEATHER_FETCH_DATA_SUCCESS = 'WEATHER_FETCH_DATA_SUCCESS';
export const WEATHER_FETCH_DATA_FAILED = 'WEATHER_FETCH_DATA_FAILED';
export const WEATHER_FETCH_DATA_PENDING = 'WEATHER_FETCH_DATA_PENDING';